### PR TITLE
fix(types): add missing shared types

### LINKED ISSUE #3201: LocaleObject type is no longer exported in v9
### Environment

Nuxt project info:                                                                            11:04:15 PM

------------------------------
- Operating System: Linux
- Node Version:     v22.11.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.6.1, @nuxtjs/color-mode@3.5.2, @nuxtjs/google-fonts@3.2.0, @nuxtjs/i18n@9.0.0, @nuxtjs/robots@4.1.11, @nuxtjs/tailwindcss@6.12.2, @pinia/nuxt@0.7.0, @vueuse/nuxt@11.2.0, nuxt-security@2.0.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-z4bplq?file=types%2Flocale.ts
Go to `types/locale.ts` file and check the `LocaleObject` import...
or launch `pnpm typecheck` in terminal to see that error.

### Describe the bug

`LocaleObject` is no longer exported from the `@nuxtjs/i18n` module (v9).

### Additional context

_No response_

### Logs

error TS2614: Module '"@nuxtjs/i18n"' has no exported member 'LocaleObject'. Did you mean to use 'import LocaleObject from "@nuxtjs/i18n"' instead?

2 import type { LocaleObject } from '@nuxtjs/i18n'

### PR DESCRIPTION
**Pull request by userquin**
### 🔗 Linked issue

resolves #3201

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

~~Nuxt module builder generating module types in types dts (node and some runtime hooks types), we use it in the default package export, but internal types created in module dts, this PR just adds a new subpackage export `./types` using `module.d.mts` with the types only and also including the subpackage inside `typesVersions` to include node10 consumers.~~
This PR includes:
- add `src/types.ts` to the build config file to add shared types to the `types` dts
- refactor CI workflow to build after stubbing to fix lint script
- run build script after stubbing before running tests (to fix typecheck: `tsc --noEmit`)

This PR also changes the default subpackage export to use `default` instead `import` (ESM only).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by userquin** [comment]
It works https://stackblitz.com/edit/github-z4bplq-q1xa2d?file=README.md

**Comment by userquin** [comment]
SB reproduction updated to use relative paths in nuxt config file (we cannot use nuxt aliases): registering also `i18n.options.ts` using relative path

**Comment by BobbieGoede** [comment]
If we're also running `build` do we still need to run `dev:prepare` before it? Doesn't `build` overwrite the output of `dev:prepare` 🤔?

**Comment by userquin** [comment]
> If we're also running `build` do we still need to run `dev:prepare` before it? Doesn't `build` overwrite the output of `dev:prepare` 🤔?

:sweat_smile:  I'll check replacing the scripts ~~, the problem is about the build script, should run also the prepare and it is not running it => create `.nuxt` stuff: if you check the starter you will see this `"prepack": "nuxt-module-build prepare && nuxt-module-build build",` (instead `build` script here)~~

**Review by BobbieGoede — APPROVED** [review]

**Pull request merged**
