### PR TITLE
fix: Memory leak

### PR DESCRIPTION
**Pull request by s00d**
### 🔗 Linked issue

https://github.com/nuxt-modules/i18n/issues/2629

This is just an example, no need to merge it. Because of this fix, everything works 10 times slower. We need a proper fix.

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by rchl** [comment]
- the existing approach where `vueI18nOptions.messages` is passed to `loadInitialMessages` and then both modified inside and returned feels unnecessarily confusing
- if the problem is that `loadInitialMessages` sets something on `messages` that blocks it from being collected then maybe it should itself take care of not doing that (by assigning stringified/parsed data maybe).

**Comment by s00d** [comment]
> * the existing approach where `vueI18nOptions.messages` is passed to `loadInitialMessages` and then both modified inside and returned feels unnecessarily confusing
> * if the problem is that `loadInitialMessages` sets something on `messages` that blocks it from being collected then maybe it should itself take care of not doing that (by assigning stringified/parsed data maybe).

The situation is more complicated here. I tried the approach you described first, but the issue is something else, which I haven't identified yet. For now, this is the only working method to detect the problem. I created the pull request just as an example to help solve the leak issue.

**Comment by BobbieGoede** [comment]
Thanks for your continued investigation of this leak @s00d! First testing of this change seems promising, but I will have a more thorough look later. 

I agree with @rchl, but as it is, this PR is helpful in proving that this may be the source of the memory leak. I'll test it further and see if I can refactor/simplify the relevant functions.

**Comment by s00d** [comment]
image
 seems the entire problem lies here: sometimes deepCopy malfunctions and returns true for objects and arrays. After that, the garbage collector can't clean up the data because it's being copied by reference into the objects. No wonder there were comments about deepCopy.
 
 
 ```js
const isObject = (val) => val !== null && typeof val === "object";
const isArray = Array.isArray;
function deepCopy(src, des) {
  if (Array.isArray(src) && Array.isArray(des)) {
    for (let i = 0; i < src.length; i++) {
      if (isObject(src[i])) {
        des[i] = deepCopy(src[i], des[i] || (Array.isArray(src[i]) ? [] : {}));
      } else {
        des[i] = src[i];
      }
    }
  } else if (isObject(src) && isObject(des)) {
    for (const key in src) {
      if (Object.prototype.hasOwnProperty.call(src, key)) {
        if (isObject(src[key])) {
          des[key] = deepCopy(src[key], des[key] || {});
        } else {
          des[key] = src[key];
        }
      }
    }
  } else {
    throw new Error("Invalid value");
  }
  return des;
}
 ```
 
 Here's a simple example of deep copying with array support. After this, the memory leak disappears, but due to the increased complexity of the function, there's a slowdown in performance.
 
 It seems that indeed it is necessary to create a translation cache to avoid processing arrays every time.
 
[Here's ](https://github.com/intlify/vue-i18n-next/pull/1675) an example, but something needs to be done about performance. If the array is large, it significantly slows down Nuxt.

**Pull request closed without merging**
