### PR TITLE
fix: Nuxt instance unavailable in `defineI18nConfig`

### PR DESCRIPTION
**Pull request by BobbieGoede**
### 🔗 Linked issue
* #2548

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
This should fix the issue of not being able to access the Nuxt instance in `defineI18nConfig`/Vue I18n config files. I added a test to confirm this, let me know if there are most cases to be tested.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kazupon — APPROVED** [review]
Wow! Great works!
LGTM!

**Comment by 50l3r** [comment]
Awesome 🥳. When will it be available?

**Comment by BobbieGoede** [comment]
This is included in the edge channel so you can try it by installing the latest edge release!

**Comment by 50l3r** [comment]
Much thanks for your job @BobbieGoede

**Pull request merged**
