### PR TITLE
refactor!: disable addDirAttribute by default

### PR DESCRIPTION
**Pull request by divine**

### CODE REVIEW

**Comment by rchl** [comment]
Please also note it in the migration docs.

**Comment by rchl** [comment]
Also found this place that needs updating: https://github.com/nuxt-community/i18n-module/blob/ffeaa7e41d025329a41f6c387010d9c3806db762/types/vue.d.ts#L17-L21

**Comment by rchl** [comment]
BTW. We can use the jsdoc `@default` tag in the comment.

```ts
  /**
   * Adds a `dir` attribute to the HTML element.
   * @default false
   */
  addDirAttribute?: boolean
```

**Comment by divine** [comment]
> BTW. We can use the jsdoc `@default` tag in the comment.
> 
> ```ts
>   /**
>    * Adds a `dir` attribute to the HTML element.
>    * @default false
>    */
>   addDirAttribute?: boolean
> ```

Update the other one as well?

https://github.com/nuxt-community/i18n-module/blob/ffeaa7e41d025329a41f6c387010d9c3806db762/types/vue.d.ts#L22-L26

**Comment by rchl** [comment]
Yes please.

**Review by rchl — APPROVED** [review]

**Comment by rchl** [comment]
Thanks!

**Pull request merged**
