### PR TITLE
refactor!: remove deprecated beforeLanguageSwitch

### PR DESCRIPTION
**Pull request by divine**
Remove deprecated beforeLanguageSwitch

### CODE REVIEW

**Comment by rchl** [comment]
Note: While doing those changes, it would be nice to at the same time start adding info about breaking changes to `migrating.md`. It will be harder to miss something if we do it right away.

**Comment by divine** [comment]
> Note: While doing those changes, it would be nice to at the same time start adding info about breaking changes to `migrating.md`. It will be harder to miss something if we do it right away.

I'm not the best at writing English migration guides, however, I will try my best.

Thanks!

**Comment by rchl** [comment]
We can reword later. It would be enough to just mention the change and suggest alternative.

**Comment by divine** [comment]
@rchl anything is left here?

Should I continue pushing PRs while this one is open?

Thanks!

**Review by rchl — APPROVED** [review]

**Comment by rchl** [comment]
Thanks!

**Pull request merged**
