### PR TITLE
fix: route param parsing

### LINKED ISSUE #1910: Optional route params get merged into one
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `modules`, `i18n`, `algolia`, `unocss`, `typescript`, `image`, `runtimeConfig`, `css`, `vite`, `build`, `app`
- Runtime Modules:  `@nuxtjs/i18n-edge@8.0.0-beta.10-27955677.afd9ab2`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@vueuse/nuxt@9.6.0`, `@unocss/nuxt@0.47.5`, `~/modules/purge-comments`, `@nuxtjs/algolia@1.5.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-6n61vd?file=nuxt.config.ts

### Describe the bug

When using optional route params and nuxti18n to translate the route, the optional params get merged into one single param.

Considering the following directory:
image
And the following route translations:
    pages: {
        'products/[[category]]/[[subcategory]]/index': {
            en: '/products/[[category]]/[[subcategory]]',
            fr: '/produits/[[category]]/[[subcategory]]',
            de: '/produkte/[[category]]/[[subcategory]]'
        },
        'products/[category]/[subcategory]/[slug]': {
            en: '/products/[category]/[subcategory]/[slug]',
            fr: '/produits/[category]/[subcategory]/[slug]',
            de: '/produkte/[category]/[subcategory]/[slug]'
        }
    }

If I navigate to /en/products/some-category/some-subcategory, I expect to see this on my route params:
params: { "category": "some-category", "subcategory":  "some-subcategory"}
Instead I get a 404.

If I navigate to /en/products/some-category, I expect to see this on my route params:
params: { "category": "some-category" }
Instead what I have is this:
params: { "categorysubcategory": "some-category" }

As you can see both optional params are merged.

This is not the case for non-optional params, everything is fine if you go to /en/products/some-category/some-subcategory/some-slug

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by BobbieGoede**
### 🔗 Linked issue
* #1910 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Resolves #1910 

This PR syncs the route segment parsing logic with that of Nuxt.

I haven't added regression tests.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kazupon — COMMENTED** [review]
Essentially, I think `parseSegument` should be exported via `nuxt/kit`. /cc @danielroe

**Comment by BobbieGoede** [comment]
I agree that would be a better long term solution, I opened an issue to track that some time ago (https://github.com/nuxt/nuxt/issues/23521). Until it's exported I think we should keep our copy of the utilities up to date so we don't break any projects.

**Comment by kazupon** [comment]
> Until it's exported I think we should keep our copy of the utilities up to date so we don't break any projects.

Yes, it is. That makes sense. I’ll merge this PR!  😉

**Review by kazupon — APPROVED** [review]

**Comment by ghost** [comment]
Sorry for the necrology but to me this is a breaking change and should be listed on the migration guide 

Coming from 8.0.0 and had some defineI18nRoute with :slug, I had to understand that this PR break the behaviour and had to change all my defineI18nRoutes

**Comment by BobbieGoede** [comment]
@BaptisteKaliop 
Sorry for the inconvenience!

You're the second person running into this being a breaking change so you're right it's a good idea to document it. This fix is a bit of an odd case since it (somehow) partially worked but was actually in a broken state 🤔.. 

Since you've just ran into this and managed to resolve it, where do you think in the documentation would be most appropriate to document this breaking change and how would you describe the changes required for projects migrating?

**Comment by ghost** [comment]
Hmm maybe we can add a small disclaimer on this page, specifically on the page-component part : https://i18n.nuxtjs.org/docs/guide/custom-paths#page-component 

Something like : 

"/!\ If you come from 8.0.0 version, path parameters has been changed from :param to [param]"

There is an example on the [scaleway documentation](https://www.scaleway.com/en/docs/storage/object/api-cli/object-storage-aws-cli/) that might illust my point 

image


Also, I don't know if you can edit the release page of the 8.0.1 on github but perhaps note this as a breaking change. This would be enough to see for devs that despite the fact it has been release on a patch version, there is a specific migration guide (with a link to the updated doc) for this

**Pull request merged**
