### PR TITLE
fix: custom routes with optional params adjusted incorrectly

### LINKED ISSUE #1242: Routes ending with an optional slug are not working anymore
### Version
nuxt-i18n: 6.27.3
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal

### Nuxt-i18n configuration
```
i18n: {
    strategy: 'prefix',
    lazy: true,
    detectBrowserLanguage: false
}
```

### Steps to reproduce

`nuxt.config.js`
```js
i18n: {
    strategy: 'prefix',
    lazy: true,
    detectBrowserLanguage: false
},
router: {
    trailingSlash: true
}
modules: [
    '~/modules/routes'
]
```

`modules/routes.js`
```js
export default async function asyncModule() {
  this.extendRoutes(function extendRoutes(routes, resolve) {
    routes.push({
      name: 'product-page',
      path: `/:product(game|software)/:uid/:slug?`, // <-- notice the optional slug used with "?"
      component: resolve(__dirname, 'pages/product.vue')
    });
  }
}
```

### What is Expected?
1. A route with a path of `/es-ES/:product(game|software)/:uid/:slug?/` should be created and listed in `$nuxt.$router.options.routes`
2. Browsing to `/game/98f76a/cod/` should return the correct page as worked in `nuxt-i18n@6.27.2`

### What is actually happening?
1. A route with a path of `/es-ES/:product(game|software)/:uid/:slug/?` gets created (Notice the `?` got moved to the end of the path) and listed in `$nuxt.$router.options.routes`.
2. Browsing to `/game/98f76a/cod/` returns a `404` error page.

### PR DESCRIPTION
**Pull request by rchl**
Don't use ufo on Vue Router route definitions as those are not
a normal paths, or not always at least.

Fixes #1242

### CODE REVIEW

**Comment by rchl** [comment]
@divine I guess it wasn't correct or necessary to use ufo in `makeRoutes`. I don't think it was a fix for anything.

**Comment by divine** [comment]
> @divine I guess it wasn't correct or necessary to use ufo in `makeRoutes`. I don't think it was a fix for anything.

Well, I just thought it would be better to handle via ufo instead of manually appending trailing slashes.

Sorry about that!

**Comment by rchl** [comment]
> > @divine I guess it wasn't correct or necessary to use ufo in `makeRoutes`. I don't think it was a fix for anything.
> 
> Well, I just thought it would be better to handle via ufo instead of manually appending trailing slashes.
> 
> Sorry about that!

Not blaming, just discussing to ensure that I'm not reverting actual fix for something.

**Comment by divine** [comment]
> Not blaming, just discussing to ensure that I'm not reverting actual fix for something.

Got it, the actual fix was in https://github.com/nuxt-community/i18n-module/blob/0527d63b99cf30fbe71bd62ded731de3a86798fc/src/templates/plugin.routing.js#L91

You were right that there are too many options and not enough tests for each option which created a regression without knowing it.

Thanks!

**Pull request merged**
