### PR TITLE
Fixed Incorrect locale returned when using different domains

### LINKED ISSUE #2374: Incorrect locale returned when using different domains
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      css, srcDir, alias, imports, modules, runtimeConfig, vite, strapi, pinia, i18n, image, postcss, tailwindcss, app
- Runtime Modules:  @pinia/nuxt@0.4.11, @vueuse/nuxt@10.4.1, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/strapi@1.9.3, @nuxt/image@1.0.0-rc.1, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-fcbka2?file=package.json

### Describe the bug

When using the Nuxt3 i18n module with different domains for each locale, the module doesn't correctly render messages for the selected locale. Instead, it offsets the selected domain's locale by one, rendering messages from a different locale.

For example, when the locale is set to 'nl' and the corresponding domain for 'nl' is visited, the messages for the 'en' locale are displayed instead of the expected 'nl' locale messages. Similarly, visiting the domain for 'fr' results in messages from the 'nl' locale being displayed.

Locales specified: 'en', 'nl', 'fr', 'de'

```typescript
// nuxt.config.ts
export default defineNuxtConfig({
  // ...

  i18n: {
    detectBrowserLanguage: false,
    vueI18n: "./i18n.config.ts",
    baseUrl: process.env.NUXT_PUBLIC_BASE_URL || "http://localhost:3000",
    lazy: true,
    langDir: "locales",
    defaultLocale: "en",
    locales: [
      {
        code: "en",
        iso: "en-US",
        name: "English",
        domain: "http://localhost:3000",
        file: "en-US.json",
      },
      {
        code: "nl",
        iso: "nl-NL",
        name: "Nederlands",
        domain: "http://nl.localhost:3000",
        file: "nl-NL.json",
      },
      // ...
    ],
    differentDomains: true,
  },

  // ...
})
```

```typescript
// i18n.config.ts
export default {
  legacy: false,
  locale: "en",
  fallbackLocale: "en",
};
```

```vue typescript
// components/LanguageSwitcher.vue
<template>
  <a v-for="locale in availableLocales" :href="switchLocalePath(locale.code)" :key="locale.code">
    {{ locale.name}}
  </a>
</template>

<script setup lang="ts">
const { locale, locales } = useI18n()
const switchLocalePath = useSwitchLocalePath()

const availableLocales = computed(() => {
  return (locales.value).filter(i => i.code !== locale.value)
})
</script>

```

### Additional Setup for Firefox Users

If you are using Firefox and encounter issues with domain navigation, you may see a warning message like `Prevented navigation to { path } due to an unknown protocol`. To fix this, you will need to update your system's hosts file to recognize the various locale-based subdomains.

#### Steps to Update the Hosts File on Windows

1. **Navigate to Hosts File Location**:  
Open your file explorer and go to `C:\Windows\System32\drivers\etc`.

2. **Open Hosts File**:  
Open the `hosts` file with a text editor like Notepad. Make sure to run the editor as an Administrator to allow edits.

3. **Add Entries**:  
Append the following lines to your hosts file. These lines map each locale-based subdomain to your local IP address (`127.0.0.1`).

    ```plaintext
    127.0.0.1       localhost
    127.0.0.1       nl.localhost
    127.0.0.1       de.localhost
    127.0.0.1       fr.localhost
    ```

4. **Save and Close**:  
Save the changes and close the text editor.

5. **Restart Firefox**:  
Close any running instances of Firefox and restart it to apply the changes.

> **Note**: These changes will affect your system globally, so exercise caution when editing system files like `hosts`.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by gaoxu529**
[…differentDomains: true and locale.domain is set with a protocol header.

### 🔗 Linked issue
https://volta.net/nuxt-modules/i18n/issues/2374

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Fixed Incorrect locale returned when using different domains

When using different domains, setting the domain to http://zh.nuxt-app.localhost or https://en.nuxt-app.localhost does not correctly retrieve the locale.code. I fixed this bug.

Resolves #2374

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
](https://volta.net/nuxt-modules/i18n/issues/2374)

### CODE REVIEW

**Comment by kazupon** [comment]
@risingsun529 
Hi!
Thank you for your contribution!
Your PR is great job!

We are always adding the issue case as a fixture and add the test here to prevent regression recurrence.
https://github.com/nuxt-modules/i18n/tree/next/specs/issues
Could you please add them as minimal ?

**Comment by gaoxu529** [comment]
@kazupon ok,I can.

**Comment by gaoxu529** [comment]
@kazupon I added the issue case as a fixture and add the test.
However, it seems that all the specs test cases are not running properly in my environment.

**Comment by kazupon** [comment]
Hi!

```
`[intlify] the message that is resolve with key 'xxxx' is not supported for jit compilation`
```

There is a waning message as shown above.
You can resolve it with syncing latest commit.

**Review by kazupon — APPROVED** [review]
Well done!
Thank you so much!

**Comment by phillipmohr** [comment]
Hi @kazupon, I'm facing the same issue: `[intlify] the message that is resolve with key 'xxxx' is not supported for jit compilation`

How can I solve the latest commit? 
I'm using NPM and updated to `8.0.0-rc.4` but the error still persists. 

Edit: For some reason this only happens within the login page of my application. All other pages seem to work just fine. 🤔

**Comment by kazupon** [comment]
That issue was fixed.
If you want to fix just now, You can install edge channel version.

**Pull request merged**
