### PR TITLE
fix: `definePageMeta` name overriding localized route name

### PR DESCRIPTION
**Pull request by BobbieGoede**
### 🔗 Linked issue
* #2581

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
While trying to figure out bundler plugins I figured there was an alternative way to tackle #2581. Maybe this is easier to break by Nuxt updates, but I feel this solution makes more sense than https://github.com/nuxt-modules/i18n/pull/2599. I still need to test this with disabled routes, and I may be missing other edge cases, please let me know.

What this PR does is transform the generated `routes.mjs` file, instead letting `name` defined in `definePageMeta` override the localized name (see [source code](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/utils.ts#L333)), we capture the locale route name suffix and combine it with the name if it exists, this makes named routes work as expected.

So in `routes.mjs` the generation would be changed like this example
```diff
-name: historyeTgp8UZZfFMeta?.name ?? "history___ja",
+name: (historyeTgp8UZZfFMeta?.name ? historyeTgp8UZZfFMeta?.name + "___ja" : undefined) ?? "history___ja",
```

What do you think @kazupon?

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kazupon** [comment]
@BobbieGoede  Thanks!

> What this PR does is transform the generated `routes.mjs` file, instead letting `name` defined in `definePageMeta` override the localized name (see [source code](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/utils.ts#L333)), we capture the locale route name suffix and combine it with the name if it exists, this makes named routes work as expected.
> 
> So in `routes.mjs` the generation would be changed like this example
> 
> ```diff
> -name: historyeTgp8UZZfFMeta?.name ?? "history___ja",
> +name: (historyeTgp8UZZfFMeta?.name ? historyeTgp8UZZfFMeta?.name + "___ja" : undefined) ?? "history___ja",
> ```

Your PR looks good!

However, this approach is more of a workaround & hack.
If possible, we hope that work-around this issue if there is a correct way to extend the URL of the named page on the nuxt.

@danielroe 
Do you have any solution or idea?

**Comment by BobbieGoede** [comment]
@kazupon 
>However, this approach is more of a workaround & hack.
If possible, we hope that work-around this issue if there is a correct way to extend the URL of the named page on the nuxt.

I agree it does feel hacky, my initial solution was #2599 but the drawback is that users would have to avoid using `definePageMeta({ name: '' })` and instead use `defineI18nRoute({ name: '' })`. 

The solution in this PR requires no changes in code or usage for users, but the drawback being that it's more likely to break. 

Personally I think the best solution would be to change the generated file from Nuxt's side, the way some data from `definePageMeta` overrides other values is inconsistent as you can see [here](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/utils.ts#L327-L338). For some reason it's just `name` and `path` that overwrite resolved page values, while `alias`, `meta`, and `redirect` overwrite values extracted from `definePageMeta`. 

~~I think I'll just open a PR to make this more consistent, but I can imagine changing this could be breaking for existing Nuxt projects. 🤔~~ This change is not as straightforward as I expected, curious to hear Daniel's perspective.

**Comment by danielroe** [comment]
I think we might consider reworking Nuxt implementation so we actually expose some page metadata at build-time (via `pages:extend`).... That will solve some edge cases like this (and with typed pages as well, where a custom `name` matters).

**Comment by BobbieGoede** [comment]
Closing this as it would break if changes are made upstream, will keep an eye on https://github.com/nuxt/nuxt/issues/24770 and if I have time later (maybe next year 😅) I'll see if I can work on resolving that.

**Pull request closed without merging**
