### PR TITLE
fix: node-libs-browser being imported on the client

### LINKED ISSUE #935: node-libs-browser included in bundle
### Version
nuxt-i18n: 6.15.3
nuxt: 2.14.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [] spa

### Reproduction Link
https://codesandbox.io/s/nuxt-i18nnode-libs-browser-kyvgu

### Steps to reproduce
execute `yarn analyze` and search for `node-libs-browser` in the client bundle

### What is Expected?
There should be no `node-libs-browser`.

### What is actually happening?
The opposite

### PR DESCRIPTION
**Pull request by janKollars**
fixes #935 node-libs-browser being imported

### CODE REVIEW

**Comment by rchl** [comment]
Thanks. Will merge once you fix the package URL.

**Comment by rchl** [comment]
I suppose also:
Resolves #907

**Comment by janKollars** [comment]
Thank you for fixing it! How embarrassing

**Comment by rchl** [comment]
Thank you for finding and figuring out the issue :)

**Pull request merged**
