### PR TITLE
fix mixin mem leak

### PR DESCRIPTION
**Pull request by Machine-Maker**
* https://nuxtjs.org/docs/2.x/directory-structure/plugins/#global-mixins

I think this is the solution to #1039

### CODE REVIEW

**Comment by rchl** [comment]
Very nice find and very surprising to me that we have this bug and had for quite a while (maybe from the start).

It seems like Nuxt is re-evaluating the plugin file on each page reload but it doesn't clear out the state within the imported Vue object.

I'm gonna discuss it a bit more with the Nuxt team. While your change fixes it, it really shouldn't be necessary and it's not clear why it is unless you know Nuxt internal behavior. And I can see pretty much every Nuxt module/plugin developer making the same "mistake" in their code if this continues to be the default Nuxt behavior.

At least it's a good thing that this only affects the dev mode and not production...

**Comment by rchl** [comment]
BTW. The https://nuxtjs.org/docs/2.x/directory-structure/plugins/#global-mixins that you've linked indeed makes a mention of having a custom property for guarding multiple mixin registrations but with plugins, the Vue itself keeps such book-keeping so it's quite unexpected that the developer would need to repeat the same logic on top of that.

And the test failures seem to indicate that that fix is possibly wrong.

**Comment by Machine-Maker** [comment]
Yeah I was unsure of how to read the test results and fix the issue. I just know that whenever I use global mixins w/nuxt, I always add the custom property to prevent duplicates. And yeah, you're totally right that it only affects developer mode. And I am surprised no one has reported this before.

**Comment by rchl** [comment]
The problem with tests is due to this change. The mixin added from `plugin.routing.js` is not overridden after being added once which causes problems when `nuxt-i18n` is built again with different options but the "old" mixin that sees old options is still registered.

This is a really messy situation...

**Comment by rchl** [comment]
FYI: @pi0 @danielroe 

Summary:
 - If you don't add extra guards for the Vue plugins or mixins registered from a plugin then you get a leak in dev mode.
 - If you add a guard, you can end up with "outdated" mixin being used during testing as apparently `jest` doesn't fully sandbox each `describe` block.

(The most likely solution for this is probably to change something in tests to work around that...)

**Comment by rchl** [comment]
It looks like @clarkdo might have made a fix for this in Nuxt: https://github.com/nuxt/nuxt.js/pull/8697

(at least for the case of registering a plugin with `Vue.use` which this module uses)

EDIT: Well, I guess that fix might not remove the mixins added through a plugin.

**Pull request closed without merging**
