### PR TITLE
feat(package): add composables export

### PR DESCRIPTION
**Pull request by dargmuesli**
### 🔗 Linked issue

n/a

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Allows to `import { useLocalePath } from '@nuxtjs/i18n/composables'` in addition to the already existing possibility to `import { useLocalePath } from '#i18n'`.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dargmuesli** [comment]
Feel free to tell me if this is an anti-pattern.

**Comment by kazupon** [comment]
Hi!
Thank you for your PR!

In my opinion, we don’t need export composable with `exports` field of `package.json`.
Because, there are no requests from communities other than nuxt to use composable. And we can import composables with `#i18n`.

nuxt does default auto import, so if you don't use auto import, we can import composable using `#i18n`.
(Oops, no docs for `#i18n` importing  😅)

**Comment by dargmuesli** [comment]
True, I thought about this because e.g. nuxt also [has `./app` exported](https://github.com/nuxt/nuxt/blob/38b6d88cfab3477edabfa37d6f97b95eefc6ae6c/packages/nuxt/package.json#L31) while providing '#app' at the same time.
@danielroe is one of those identifiers to be preferred or recommended? :bulb:

**Comment by danielroe** [comment]
I would recommend importing from `#imports` instead of either of them.

**Pull request closed without merging**
