### PR TITLE
fix: loop redirection

### LINKED ISSUE #1843: strategy prefix not work on spa mode
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.0.0`
- Builder:          `vite`
- User Config:      `modules`, `css`, `ssr`, `swiper`, `app`, `runtimeConfig`, `vite`, `postcss`, `i18n`
- Runtime Modules:  `nuxt-swiper@0.1.9`, `@vueuse/nuxt@9.11.0`, `@nuxtjs/device@3.0.0`, `@nuxtjs/i18n@8.0.0-beta.9`
- Build Modules:    `-`
------------------------------

### Reproduction

`nuxt.config.ts`
```javascript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ["@nuxtjs/i18n"],
  css: ["~/assets/css/main.css"],
  ssr: false,
  vite: {
    css: {
      preprocessorOptions: {
        sass: {
          additionalData: '@import "@/assets/styles/variable.sass"',
        },
      },
    },
  },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  i18n: {
    strategy: "prefix",
    defaultLocale: "zh",
    locales: [
      {
        name: "English",
        code: "en",
        iso: "en-hk",
        file: "en.json",
      },
      {
        name: "繁體",
        code: "zh",
        iso: "zh-hant-hk",
        file: "zh.json",
      },
    ],
    lazy: true,
    langDir: "locales/",
    vueI18n: {
      silentTranslationWarn: true,
      legacy: false,
    },
  },
});

```

### Describe the bug

As [nuxt.i18n documentation](https://v8.i18n.nuxtjs.org/guide/routing-strategies) mentioned that `all routes will have a locale prefix.`, but in my case, the default locale will NOT auto add the locale in URL.

### Additional context

My Excecptaion:
When user enter home route (localhost:3000) , it will auto go to localhost:3000/zh

If I set `ssr` to `true` in `nuxt.config.ts`, it will works as expect, but my application is static(`npm run generate`), instead of SSR(`npm run build`)

### Logs

_No response_

### LINKED ISSUE #1851: SSG freezed the browser
### Environment
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `pages`, `css`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9-27926914.891e694`
- Build Modules:    `-`
------------------------------

### Reproduction

test.stefanotesla.it

### Describe the bug

Sorry for short implementation I'm from Mobile and the Project is At the office

I have problems with SSG, once i load the site and visit it the browser freez.

I tried with Chrome and a Virgin installati on of Firefox

All details and reproduction here:

https://github.com/nuxt/nuxt/issues/18876

I asked to the nuxt team bit they think is related to i18n

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by kazupon**
### 🔗 Linked issue

resolve #1851 
resolve #1843 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by StefanoTesla** [comment]
https://user-images.githubusercontent.com/92517402/218404170-e88e2079-fdac-4ee6-b4bf-a20034fe69d6.mp4

I have a refresh loop now

**Comment by kazupon** [comment]
You need to install edge channel version.
https://www.npmjs.com/package/@nuxtjs/i18n-edge

**Comment by StefanoTesla** [comment]
package.json
`  "devDependencies": {
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
    "@volar-plugins/vetur": "latest",
    "nuxt": "^3.2.0"
  },`

package.lock.json
`    "node_modules/@nuxtjs/i18n": {
      "name": "@nuxtjs/i18n-edge",
      "version": "8.0.0-beta.9-27936380.225e0b6",
      "resolved": "https://registry.npmjs.org/@nuxtjs/i18n-edge/-/i18n-edge-8.0.0-beta.9-27936380.225e0b6.tgz",
      "integrity": "sha512-Eo5lAE/L3Bgcy7YjtZX9tL5VwI1Dd+3UU0VgXJVGkWVR4tJrjZp7MpyP9bvVgzjiPrDouImOEmVwythZgLlH3A==",
      "dev": true,`

peformed `npm update`, `npm cache clear --force` `npm update` `npx nuxi update` `npm update` synced the repo on github olso

**Comment by kazupon** [comment]
Hi!
Unfortunately, I could not reproduce loop redirection.
I think your browser cookie may have been corrupted by the reproduction environment. Please check once you have cleared your browser cache and cookies.

**Comment by StefanoTesla** [comment]
this is very wired...homepage in default language works well, if I load english page I have a 301 to the page en/
it load but once all files are loaded this restart to load all the page, you can check test.stefanotesla.it works well, but  test.stefanotesla.it/en have a redirect loop

image

**Comment by dargmuesli** [comment]
I can confirm this issue. Currently visible on https://b0d8d43b.jonas-thelemann.pages.dev/legal-notice/, but not on https://b0d8d43b.jonas-thelemann.pages.dev/. I'm going to deploy a fix (downgrade) for my page ~once you, @kazupon, got the chance to check those links out and react with a comment to this comment, please~ now, as I can give you the single deployment id in the links you see.

I've opened https://github.com/nuxt-modules/i18n/issues/1856.

**Comment by motion-work** [comment]
@kazupon has this fix been testing with `differentDomains: true` + `yarn generate`? We've been struggling with the same issue, also after upgrading to beta 10.

```js
i18n: {
    debug: false,
    defaultLocale: 'it',
    detectBrowserLanguage: false,
    lazy: true,
    langDir: 'lang/',
    strategy: 'prefix_except_default',
    differentDomains: true,
    locales: [
      {
        code: 'de',
        name: 'Deutsch',
        iso: 'de-CH',
        file: 'de.json',
        domain: process.env.DOMAIN_DE || 'http://mobiliar.novu.io:8080',
      },
      {
        code: 'fr',
        name: 'Français',
        iso: 'fr-CH',
        domain: process.env.DOMAIN_FR || 'http://mobiliere.novu.io:8081',
        file: 'fr.json',
      },
      {
        code: 'it',
        name: 'Italiano',
        iso: 'it-CH',
        domain: process.env.DOMAIN_IT || 'http://mobiliare.novu.io:8082',
        file: 'it.json',
      },
    ],
  },
```

**Pull request merged**
