### PR TITLE
fix: use `createResolver` from kit

### PR DESCRIPTION
**Pull request by ineshbose**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR aims to refactor all `resolve` functions to use `createResolver` from `@nuxt/kit` (this should also help in development steps such as not re-triggering build for every `pnpm run dev` but rather use stubs).

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ineshbose** [comment]
Files with `resolve`:

1. module.ts
2. alias.ts
3. bundler.ts
4. dirs.ts
5. pages.ts
6. utils.ts

**Comment by kazupon** [comment]
Good contribution!
I appreciate your help!

**Comment by ineshbose** [comment]
Just realised that this in the TODO as well 😄 https://github.com/nuxt-modules/i18n/blob/7943ca10a11ed07dc60b4bf3aa9896f8069ecd0f/TODO.md?plain=1#L8

**Comment by ineshbose** [comment]
Sorry need to close - should declutter some PRs! Will be reopen when convenient.

**Pull request closed without merging**
