### PR TITLE
refactor: integrate `localizeRoutes` from `vue-i18n-routing`

### PR DESCRIPTION
**Pull request by BobbieGoede**
### 🔗 Linked issue
* #2351 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
This PR moves adds the code and tests for `localizeRoutes` from `vue-i18n-routing`. 

@kazupon do I understand correctly from [your comment](https://github.com/intlify/routing/pull/79#issuecomment-1793307251) that we want to move all of `vue-i18n-routing` inside of this repository? Would we want to add it as a package inside this repository or fully integrate it in the module code?

Besides the above reasoning, the main motivation behind wanting to add this code is to work on fixing #2351. I figured I would add it first without making any changes. Will be refactoring and possibly fixing the issue in a separate PR.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kazupon** [comment]
> do I understand correctly from [your comment](https://github.com/intlify/routing/pull/79#issuecomment-1793307251) that we want to move all of `vue-i18n-routing` inside of this repository?

Yes! we should move all to this repository. 
vue-i18n-routing has somes code both version supporting for Vue 2 and Vue 3 with vue-demi.
we don’t need to move the codes for Vue 2.

> Would we want to add it as a package inside this repository or fully integrate it in the module code?

I would prefer to move it as an integrated module code, if it is moved as a separate package in monorepo, it would be very cumbersome to manage and require npm publish of the package. 

Even if we were to manage it in the pnpm workspace as a simple priavte pacakge without using npm publish, it would still be cumbersome to manage because the code would have to be inlined and included in nuxt i18n.

**Comment by BobbieGoede** [comment]
I have refactored and simplified the route localization further, now it mostly doesn't rely on imports from `vue-i18n-routing` (probably does indirectly). 

>I would prefer to move it as an integrated module code, if it is moved as a separate package in monorepo, it would be very cumbersome to manage and require npm publish of the package.

Sounds good! It will definitely make it easier to change/fix some things (such as https://github.com/nuxt-modules/i18n/issues/2628), will slowly work to refactor and integrate the code over multiple PRs.

Also I notice the tests introduced by https://github.com/nuxt-modules/i18n/pull/2580 are flaky, I'll have to look into that sometimes.

**Comment by kazupon** [comment]
@BobbieGoede 

> Sounds good! It will definitely make it easier to change/fix some things (such as #2628), will slowly work to refactor and integrate the code over multiple PRs.

Good job!
Okay, so, Are you still going to make any changes?
If not, I would like to merge them! :)

**Comment by BobbieGoede** [comment]
@kazupon 
Ah I should have switched it to draft when I was still editing 😅, this PR is all done and can be merged

**Comment by kazupon** [comment]
@BobbieGoede 
okay,
when you will finish your work, please ping me.

**Comment by BobbieGoede** [comment]
> @BobbieGoede okay, when you will finish your work, please ping me.

It is finished!

**Review by kazupon — APPROVED** [review]
great works!
your are perfect! 💯 

LGTM!

**Pull request merged**
