### PR TITLE
fix: cannot resolve `localePath`  correctly

### LINKED ISSUE #2523: LocalePath double encoding URLs, causing 404s
### Environment

- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      experimental, routeRules, devtools, modules, runtimeConfig, security, app, i18n, nitro
- Runtime Modules:  nuxt-security@0.14.4, @nuxtjs/i18n@8.0.0-rc.5, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.5.1, nuxt-headlessui@1.1.4, @vueuse/nuxt@10.5.0, nuxt-lazy-hydrate@1.0.0
- Build Modules:    -

### Reproduction

Use localePath with any URL path that includes spaces.

### Describe the bug

Using useLocalPath on any URL that includes spaces is double encoding the path, causing the route to fail to resolve (404).

For example, the following:

`const { localePath } = useLocalePath();

const url = localePath('path/as a test')`

...will result in a url like "/path/as%2520a%2520test". It should instead be "/path/as%20a%20test", but the function appears to be double encoding, causing the %20 to change to %2520 (which fails to resolve as a route, and causes a 404).

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #2525: Hash in NuxtLink don't work with LocalePath
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, build, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ynzoxn

### Describe the bug

When you add a hash to a link with `localePath` like this:
```HTML
<NuxtLink :to="localePath({ name: 'about', hash: '#myHash' })">
  My link with a hash
</NuxtLink>
```

The Hash of link is not add to the generated tag
```HTML
<a href="/en/about">My link with a hash</a> // #myHash is missing
```

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by kazupon**
### 🔗 Linked issue

resolve #2523 
resolve #2525 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This issues is fixed via `vue-i18n-routing`

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kazupon** [comment]
@BobbieGoede 
Can you add tests for cases #2523 and #2525 for regression? 🙏

**Comment by kazupon** [comment]
You can push `fix/bump-deps` branch.

**Comment by BobbieGoede** [comment]
> @BobbieGoede Can you add tests for cases #2523 and #2525 for regression? 🙏

Added the regression tests. 

For #2523 I had to guess the intended usage as there was no minimal reproduction.. The example given in the issue description would not have worked, so I made the assumption that the following changes would have been the intended usage.
```diff
const { localePath } = useLocalePath();
-const url = localePath('path/as a test')`
+const url = localePath(`/path/${encodeURI('as a test')}`)
```

 Let me know if this should be different!

**Comment by kazupon** [comment]
@BobbieGoede 
Thanks for your testing!

**Pull request merged**
