### PR TITLE
Modify Guide Description 🍀

### PR DESCRIPTION
**Pull request by bottlehs**
Difficult for beginners to know

### CODE REVIEW

**Comment by rchl** [comment]
I'm fine with this change but we should be consistent and change the style on all pages that have an example configuration.

And also make a similar changes in `es` documentation.

**Comment by bottlehs** [comment]
> I'm fine with this change but we should be consistent and change the style on all pages that have an example configuration.
> 
> And also make a similar changes in `es` documentation.

https://github.com/nuxt-community/i18n-module/pull/947/commits/877345cf6b6efc5b88a6ac1bfe6808f545ff80ea

Please confirm

**Comment by rchl** [comment]
> [877345c](https://github.com/nuxt-community/i18n-module/commit/877345cf6b6efc5b88a6ac1bfe6808f545ff80ea)
> 
> Please confirm

Please make the same change in `es` documentation.

**Comment by bottlehs** [comment]
> > [877345c](https://github.com/nuxt-community/i18n-module/commit/877345cf6b6efc5b88a6ac1bfe6808f545ff80ea)
> > Please confirm
> 
> Please make the same change in `es` documentation.

Please Confirm 

#948, #947

**Comment by rchl** [comment]
Please make both changes in the same PR.

**Pull request closed without merging**
