### PR TITLE
fix: missing hash query param in `load` hook for virtual conf

### LINKED ISSUE #2211: missing query hash param when loading virtual conf
### Environment

```shell
npx nuxi info
Nuxi 3.6.2                                                                                                                                                                14:22:00
                                                                                                                                                                          14:22:00
RootDir: D:/work/projects/userquin/GitHub/userquin/vuetify-nuxt-module-i18n-beta13                                                                                        14:22:00
Nuxt project info:                                                                                                                                                        14:22:00

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.6
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

Fork https://github.com/userquin/vuetify-nuxt-module/ and then chekout `userquin/fix-rtl-locale-support` branch: 
https://github.com/userquin/vuetify-nuxt-module/tree/userquin/fix-rtl-locale-support (I'm working in the PR to add RTL support to Vuetify 3)

Run `pnpm install`, and then you can run:
- `nr dev:prepare && nr dev`: for single json file per locale
- `nr dev:prepare:multiple-json && nr dev:multiple-json`: for multiple json files per locale

### Describe the bug

When resolving i18n config file missing hash query param:

beta 13

imagen

beta 12

imagen

### Additional context

I'm preparing a PR to fix the error, PR in a few minutes.

Patching proxy module just works:

imagen

imagen

### Logs

_No response_

### PR DESCRIPTION
**Pull request by userquin**
### 🔗 Linked issue

#2211 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #2211

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kazupon — APPROVED** [review]
Thank you for your PR!

Oh, I deleted the hash, that was my mistake 😓 
Thanks!

**Comment by userquin** [comment]
@kazupon still not working, I've been trying to fix the error for 2 days, the PR was in draft

**Comment by kazupon** [comment]
@userquin 
You can send the PR again!

**Comment by userquin** [comment]
@kazupon the problem is this:
<details>
<summary>debug output: SSR</summary>

```shell
isSSG false                                                                                                                                                               11:48:43  
useCookie on setup false                                                                                                                                                  11:48:43  
defautlLocale on setup en-US                                                                                                                                              11:48:43  
detectLocale: initialLocale - en-US                                                                                                                                       11:48:43  
detectLocale: detectBrowserLanguage (browserLocale, stat, reason, from) -  false unknown unknown                                                                          11:48:43  
detectLocale: finaleLocale first (finaleLocale, strategy) -  no_prefix                                                                                                    11:48:43  
detectLocale: finaleLocale second (finaleLocale, detectBrowserLanguage) - en-US false                                                                                     11:48:43  
detectLocale: finalLocale last (finalLocale, defaultLocale) - en-US en-US                                                                                                 11:48:43  
detectLocale: finalLocale - en-US                                                                                                                                         11:48:43  
first detect initial locale en-US                                                                                                                                         11:48:43  
final initial locale: en-US                                                                                                                                               11:48:43  
locale-changing middleware {                                                                                                                                              11:48:43  
  fullPath: '/_nuxt/@id/__x00__@nuxtjs/i18n/null',
  hash: '',
  query: {},
  name: undefined,
  path: '/_nuxt/@id/__x00__@nuxtjs/i18n/null',
  params: {},
  matched: [],
  meta: {},
  redirectedFrom: undefined,
  href: '/_nuxt/@id/__x00__@nuxtjs/i18n/null'
} {
  fullPath: '/_nuxt/@id/__x00__@nuxtjs/i18n/null',
  path: '/_nuxt/@id/__x00__@nuxtjs/i18n/null',
  query: {},
  hash: '',
  name: undefined,
  params: {},
  matched: [],
  meta: {},
  redirectedFrom: undefined,
  href: '/_nuxt/@id/__x00__@nuxtjs/i18n/null'
}
```
</details>

<details>
<summary>Configuration</summary>

```ts
// nuxt.config.ts
i18n: {
    locales: availableLocales,
    lazy: true,
    strategy: 'no_prefix',
    detectBrowserLanguage: false, /* {      fallbackLocale: 'en-US',
      useCookie: false,
    } */
    langDir,
    defaultLocale: 'en-US',
    types: 'composition',
    pages: undefined,
    dynamicRouteParams: false,
    skipSettingLocaleOnNavigate: true,
    debug: true,
    vueI18n: './config/i18n.config.ts',
  },
```

```ts
// ./config/i18n.config.ts
import { availableLocales, datetimeFormats, numberFormats, pluralRules } from './i18n'

export default {
  legacy: false,
  availableLocales: availableLocales.map(l => l.code),
  fallbackLocale: 'en-US',
  fallbackWarn: true,
  pluralRules,
  datetimeFormats,
  numberFormats,
  globalInjection: true,
  missingWarn: true,
}
```
</details>

**Comment by userquin** [comment]
@kazupon reverted wrong commit, you should revert only https://github.com/nuxt-modules/i18n/pull/2212, the lazy load is ok, the ternary is wrong: https://github.com/nuxt-modules/i18n/pull/2193 PR should be in next branch

**Comment by userquin** [comment]
It seems we need to extract the locale from another place, `query.locale` seems to be null, should extracted from the path

imagen

**Pull request merged**
