### PR TITLE
Revert "fix: lazy load i18n files"

### PR DESCRIPTION
**Pull request by kazupon**
Reverts nuxt-modules/i18n#2193

### CODE REVIEW

**Comment by userquin** [comment]
@kazupon why do you revert also the lazy commit ?

**Comment by kazupon** [comment]
Lazy load does not works.
You can try it in the nuxt-i18n playground.

**Comment by userquin** [comment]
It is working in my vuetify nuxt module with single and multiple files per locale:
https://github.com/userquin/vuetify-nuxt-module

I Will check it later in my local.

**Comment by userquin** [comment]
@kazupon the i18n playground seems to be working with a few changes from #2219 , the playground should change the lang when clicking on the links no?

imagen

imagen

**Comment by userquin** [comment]
EDIT: it seems something wrong with the imports, check the screenshot here: https://github.com/nuxt-modules/i18n/pull/2212#issuecomment-1634312968

About the null entry, in the playground here also missing some entry/request, the virtual entry is not there.

I guess it is something in Nuxt, Nuxt DevTools inspector isn't able to intercept virtual modules when virtual module using default Vite name convention (prefixing ids with `\0`).

I'll try to change the resolved virtual ids here and check if it is working...


imagen

**Comment by kazupon** [comment]
Thanks!
I look forward to PR from you :)

**Pull request merged**
