### PR TITLE
fix: encode `switchLocalePath` during SSR replacement

### LINKED ISSUE #3042: Experimental switchLocalePathLinkSSR causing possible XSS vector
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.10.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      site, debug, app, ssr, telemetry, devtools, sourcemap, modules, vite, nitro, runtimeConfig, i18n, hooks, graphqlMiddleware, multiCache, sitemap, robots, svgSprite, alias, purgecss, htmlValidator
- Runtime Modules:  @nuxtjs/html-validator@1.8.2, @nuxtjs/i18n@8.3.1, @nuxtjs/sitemap@5.2.0, @nuxtjs/robots@3.0.0, @nuxtjs/svg-sprite@1.0.2, @pinia/nuxt@0.5.1, nuxt-graphql-middleware@4.0.0, nuxt-multi-cache@3.1.1, nuxt-purgecss@2.0.0, @nuxt/test-utils/module@3.13.1
- Build Modules:    -

### Reproduction

Minimal Repro: https://github.com/KilianSSL/i18n-ssr-repro

Disable javascript, to best review the SSR response.

1. Set experimental switchLocalePathLinkSSR flag to true
2. Create a wildcard page like /pages/[...slug].vue
3. Make sure you have a language switcher utilizing `<SwitchLocalePathLink>`
4. Navigate to a page like: `http://localhost:3000/fr/%22%3Exss/`
5. If not manually overridden/sanitized via 

  ```
 setI18nParams({
    fr: { slug: '' },
    de: { slug: '' },
  })  
```

  the `">xss/` portion of the URL will cause `<SwitchLocalePathLink>` to output invalid HTML that will render whatever comes after `">xss/`.

### Describe the bug

The bug seems to be caused by `<SwitchLocalePathLink>` defaulting to the current URL parameters, if not set otherwise via `setI18nParams`. The parameters are not being sanitized before they're used in the generated HTML.

grafik

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by BobbieGoede**
### 🔗 Linked issue
* https://github.com/nuxt-modules/i18n/issues/3042

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
This should resolve #3042, but if I'm overlooking something please let me know.

@kazupon 
I created a [`v8` branch](https://github.com/nuxt-modules/i18n/tree/v8) which diverts from `main` at 7930a2773311bef05bd98a3a98540ce17b6a7d6b, I have also cherry picked some changes from the main branch where possible.

If this PR gets merged it will need to be added to the `v8` branch as well, will the normal release flow work from that branch? 🤔

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kazupon — APPROVED** [review]
Thank you!
The release flow using GitHub Actions is difficult, so we need to release manually.

**Comment by pmnzt** [comment]
Something is broken about this function, it now returns nothing 
@kazupon 
@BobbieGoede

**Comment by BobbieGoede** [comment]
> Something is broken about this function, it now returns nothing 
> @kazupon 
> @BobbieGoede 

Can you open a new issue and provide a minimal reproduction? 🙏

**Comment by pmnzt** [comment]
> > Something is broken about this function, it now returns nothing
> > @kazupon
> > @BobbieGoede
> 
> Can you open a new issue and provide a minimal reproduction? 🙏

here https://github.com/nuxt-modules/i18n/issues/3051

**Pull request merged**
