### PR TITLE
feat: Support multiple languages on one or more domains while having different domains

### LINKED ISSUE #2418: multiple languages per domain
### Describe the feature

add ability to specify prefix for each language on top of domain.

```
        locales: [
            {
                code: 'sl',
                domain: 'domain1.com',
            },
            {
                code: 'hr',
                domain: 'domain1.hr',
            },
            {
                code: 'hu',
                domain: 'domain2.com',
                prefix: '/hu'
            },
            {
                code: 'en',
                domain: 'domain2.com',
                prefix: '/en'
            },
    ]
```

so paths would look like this:

domain1.com => sl lang
domain1.hr => hr lang

domain2.com/en => en lang
domain2.com/hu => hu lang

if user hits "domain2.com" it redirects him to "domain2.com/defaultLocale"

i am willing to implement this myself but i need a bit of guidance since i am new to nuxt / ts :)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by bjerggaard**
### 🔗 Linked issue

#2418

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This change will support different domains while having more than one language on one or more of the domains.
In order to support the various strategies one must set a `domainDefault: true` on the default/fallback locale on each domain.

Resolves #2418

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by WooHoo-Wu** [comment]
This feature is urgently needed, please release the official version as soon as possible, thank you! ! !

**Comment by BobbieGoede** [comment]
Thanks for contributing! 

This PR looks great, I'm happy to see this doesn't seem to introduce any breaking changes. I'm not seeing anything glaring that needs to be changed, what do you think @kazupon?

The configuration for `locales` is getting a bit complicated, which isn't necessarily an issue but we could consider changing this for v9, feel free to suggest changes in the roadmap discussion https://github.com/nuxt-modules/i18n/discussions/2814 if you have ideas.

**Review by BobbieGoede — APPROVED** [review]

**Review by kazupon — APPROVED** [review]
Sorry, my late reply.
Looks good feature too me

Thanks

**Comment by bezoerb** [comment]
This kind of introduces breaking changes as we're not able to use [Custom route paths](https://v8.i18n.nuxtjs.org/guide/custom-paths#custom-route-paths) with different domains anymore.
Before this it was possible to omit the `strategy` option and have localized paths without prefix. This is not possible anymore so we need to downgrade to v8.2.0

Is there any chance to also bring back the old behavior by allowing `strategy: 'no_prefix'` together with `differentDomains: true`?

I guess this change here introduces the breaking change:
https://github.com/nuxt-modules/i18n/pull/2705/files#diff-692e2f97144046b5098ccb96849867854a2811345bd2ee991c0fc6d2e47f4a38L34



/cc @BobbieGoede @kazupon

**Pull request merged**
